// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_order_posted_by_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_order_posted_by_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201711191000183_add_order_posted_by_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
